@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package vault_work_station.blocks;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;