@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.lawliet.companionWorkStation.init;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;