@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.lawliet.companionWorkStation.blocks.entity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;